version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
    versioning-strategy: increase
    ignore:
      - dependency-name: typescript
        versions:
          - ">= 3.10.a"
      - dependency-name: "@types/node"
        versions:
          - ">= 11.a"

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
