name: update pr
on:
  issue_comment:
    types: [created]

jobs:
  update_pr_branch:
    name: Update branch
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '@projen update') }}
    runs-on: ubuntu-latest
    steps:
      - name: PR head
        env:
          PULL_REQUEST_URL: ${{ github.event.issue.pull_request.url }}
          REPOSITORY_URL: ${{ github.repositoryUrl }}
        run: |
          BRANCH=$(curl --silent $PULL_REQUEST_URL | jq ".head.ref")
          git clone $REPOSITORY_URL -b $BRANCH workdir
          cd workdir
          ls
#       - uses: actions/checkout@v2
#         env:
#           REF: github.event.issue.pull_request
#       - run: yarn install --frozen-lockfile
#       - run: yarn projen
#       - run: yarn build
#       - name: Commit files
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git commit -m "chore: generate files" -a
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}
